name: test_coverage
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 0.2.3
homepage: https://github.com/pulyaevskiy/test-coverage
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.66.0 <3.0.0'

executables:
  test_coverage:

dependencies:
  coverage: ^0.12.1
  path: ^1.6.1
  lcov: ^4.1.0

dev_dependencies:
  test: ^1.0.0
